config/routes.rb
require 'sidekiq/web'
Mrtablueline::Application.routes.draw do

  get "graphs/index"

    resources :reports
  namespace :mrta do
    resources :tracks
    resources :projects do
      get 'gentracks', on: :member
      get 'showtracks', on: :member
    end
    resources :graphs
  end

  resources :sections

  match "/progresses"  => "progresses#index"
  match "/progresses/station/:id" => "progresses#show"
  match "/progresses/report/:id" => "progresses#report"
  match "/progresses/announce/:id" => "progresses#announce"
  match "/progresses/effect/:id" => "progresses#effect"
  match "/progresses/effect/" => "progresses#effect"
  match "/progresses/effect_latest/" => "progresses#effect_latest"
  match "/progresses/effect_monthly/" => "progresses#effect_monthly"
  match "/progresses/report_latest/" => "progresses#report_latest"
  match "/progresses/report_monthly/" => "progresses#report_monthly"
  match "/progresses/activity/" => "progresses#activity"
  match "/progresses/activity_latest/" => "progresses#activity_latest"
  match "/progresses/activity_monthly/" => "progresses#activity_monthly"
  match "/fullmap" => "progresses#fullmap"

  resources :announces, :only => [:show]

  resources :activities , :only => [:show]
  resources :geopoints
  resources :pages

  namespace :admin do resources :geonodes end

  mount Ckeditor::Engine => '/ckeditor'

  get "home/index"
  get "home/underconstruction"
  get "welcome/index"
  root to: "home#index"
  get '/graph', to: "home#graph"
  mount Sidekiq::Web, at: 'sidekiq'

  match "/mrtamap" => "home#mrtamap"
  devise_for :users
  namespace :admin do
    resources :users do
      member do
        get 'assign_supervisor_role'
        get 'remove_supervisor_role'
        get 'assign_mrtaadmin_role'
        get 'remove_mrtaadmin_role'
        get 'assign_author_role'
        get 'remove_author_role'
      end
    end

  end
  namespace :backoffice do
    resources :application, :only => [:index]
    resources :pages
    resources :reports do
      get 'approve', :on => :member
    end

    resources :stations
    resources :profiles
    resources :companies
    resources :activities do
      get 'approve', :on => :member
    end

    resources :mediatypes
    resources :effects
    resources :sections
    resources :announces do
      get 'approve', :on => :member
    end
  end

   mount Ckeditor::Engine => "/ckeditor"
end

app/controllers/backoffice/activities_controller.rb
class Backoffice::ActivitiesController < ApplicationController
  layout 'backoffice'
  before_filter :authenticate_user!
  load_and_authorize_resource
    # GET /activities
  # GET /activities.json
  def index
    if (current_user.has_role? :admin) or (current_user.has_role? :mrtaadmin)
      @activities = Activity.unscoped.all.desc(:created_at).to_a
    else
      @activities = current_user.activities.unscoped.desc(:created_at).to_a

    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show

    if (current_user.has_role? :admin) or (current_user.has_role? :mrtaadmin)
      @activity = Activity.find(params[:id])
    else
      @activity = current_user.activities.find(params[:id])
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new
    @allmedias = Mediatype.all
    @selectedmedia = Mediatype.all.to_a.first
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
    @allmedias = Mediatype.all
    @selectedmedia = @activity.mediatype
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])
    @activity.user_id = current_user._id
    respond_to do |format|
      if @activity.save
        ApproveSystem.perform_async(@activity.id,'activities','Activity')
        format.html { redirect_to backoffice_activities_path, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to backoffice_activities_path, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to backoffice_activities_url }
      format.json { head :no_content }
    end
  end
  def approve
    @activity = Activity.find(params[:id])
    if @activity.approved
       @activity.approved = false
    @activity.approvedby= "unapproved #{current_user.name || current_user.email}"  + Time.now.strftime("on %m/%d/%Y at %I:%M%p")
    else
       @activity.approved = true
       @activity.approvedby= "approved #{current_user.name || current_user.email}"  + Time.now.strftime("on %m/%d/%Y at %I:%M%p")

    end

    @activity.save
    respond_to do |format|
      format.html { redirect_to backoffice_activities_path }
    end
  end

end

app/controllers/backoffice/announces_controller.rb
class Backoffice::AnnouncesController < ApplicationController
  layout 'backoffice'
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /announces
  # GET /announces.json
  def index
    if (current_user.has_role? :admin) or (current_user.has_role? :mrtaadmin)
      @announces = Announce.all.desc(:created_at).to_a
    else
      @announces = current_user.announces.desc(:created_at).to_a
    end


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @announces }
    end
  end

  # GET /announces/1
  # GET /announces/1.json
  def show
    @announce = Announce.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @announce }
    end
  end

  # GET /announces/new
  # GET /announces/new.json
  def new
    @announce = Announce.new
    @alleffects = Effect.all.to_a
    @selectedeffect = Effect.all.to_a.first
    @announce.build_geopoint
    @lat = 13.7522222
    @lng = 100.4938889
    @json = '[{"lng": "100.4938889", "lat": "13.7522222"}]'


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @announce }
    end
  end

  # GET /announces/1/edit
  def edit
    Announce
    @announce = Announce.find(params[:id]) rescue nil
    @alleffects = Effect.all.to_a
    @json = @announce.geopoint.to_gmaps4rails
  end

  # POST /announces
  # POST /announces.json
  def create
    @announce = Announce.new(params[:announce])
    @announce.user_id = current_user._id

    respond_to do |format|
      if @announce.save
        ApproveSystem.perform_async(@announce.id,'announces','Announce')
        format.html { redirect_to backoffice_announces_path, notice: 'Announce was successfully created.' }
        format.json { render json: @announce, status: :created, location: @announce }
      else
        format.html { render action: "new" }
        format.json { render json: @announce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /announces/1
  # PUT /announces/1.json
  def update
    @announce = Announce.find(params[:id])

    respond_to do |format|
      if @announce.update_attributes(params[:announce])
        format.html { redirect_to backoffice_announces_path, notice: 'Announce was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @announce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announces/1
  # DELETE /announces/1.json
  def destroy
    @announce = Announce.find(params[:id])
    @announce.destroy

    respond_to do |format|
      format.html { redirect_to backoffice_announces_url }
      format.json { head :no_content }
    end
  end
  def approve
    @announce = Announce.find(params[:id])
    if @announce.approved
       @announce.approved = false
    @announce.approvedby= "unapproved #{current_user.name || current_user.email}"  + Time.now.strftime("on %m/%d/%Y at %I:%M%p")
    else
       @announce.approved = true
       @announce.approvedby= "approved #{current_user.name || current_user.email}"  + Time.now.strftime("on %m/%d/%Y at %I:%M%p")

    end

    @announce.save
    respond_to do |format|
      format.html { redirect_to backoffice_announces_path }
    end
  end
end

app/controllers/backoffice/application_controller.rb
class Backoffice::ApplicationController < ApplicationController
  layout 'backoffice'
  before_filter :authenticate_user!
   #load_and_authorize_resource

  def index
  end
  protected

    def ckeditor_filebrowser_scope(options = {})
      super({ :assetable_id => current_user.id, :assetable_type => 'User' }.merge(options))
    end
end

app/controllers/backoffice/companies_controller.rb
class Backoffice::CompaniesController < ApplicationController
  layout 'backoffice'
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to backoffice_companies_path, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to backoffice_companies_path, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to backoffice_companies_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/backoffice/effects_controller.rb
class Backoffice::EffectsController < ApplicationController
  layout 'backoffice'
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /effects
  # GET /effects.json
  def index
    @effects = Effect.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @effects }
    end
  end

  # GET /effects/1
  # GET /effects/1.json
  def show
    @effect = Effect.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @effect }
    end
  end

  # GET /effects/new
  # GET /effects/new.json
  def new
    @effect = Effect.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @effect }
    end
  end

  # GET /effects/1/edit
  def edit
    @effect = Effect.find(params[:id])
  end

  # POST /effects
  # POST /effects.json
  def create
    @effect = Effect.new(params[:effect])

    respond_to do |format|
      if @effect.save
        format.html { redirect_to backoffice_effects_path, notice: 'Effect was successfully created.' }
        format.json { render json: @effect, status: :created, location: @effect }
      else
        format.html { render action: "new" }
        format.json { render json: @effect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /effects/1
  # PUT /effects/1.json
  def update
    @effect = Effect.find(params[:id])

    respond_to do |format|
      if @effect.update_attributes(params[:effect])
        format.html { redirect_to backoffice_effects_path, notice: 'Effect was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @effect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /effects/1
  # DELETE /effects/1.json
  def destroy
    @effect = Effect.find(params[:id])
    @effect.destroy

    respond_to do |format|
      format.html { redirect_to backoffice_effects_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/backoffice/mediatypes_controller.rb
class Backoffice::MediatypesController < ApplicationController
  layout 'backoffice'

before_filter :authenticate_user!
load_and_authorize_resource
  # GET /mediatypes
  # GET /mediatypes.json
  def index
    @mediatypes = Mediatype.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mediatypes }
    end
  end

  # GET /mediatypes/1
  # GET /mediatypes/1.json
  def show
    @mediatype = Mediatype.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mediatype }
    end
  end

  # GET /mediatypes/new
  # GET /mediatypes/new.json
  def new
    @mediatype = Mediatype.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mediatype }
    end
  end

  # GET /mediatypes/1/edit
  def edit
    @mediatype = Mediatype.find(params[:id])
  end

  # POST /mediatypes
  # POST /mediatypes.json
  def create
    @mediatype = Mediatype.new(params[:mediatype])

    respond_to do |format|
      if @mediatype.save
        format.html { redirect_to backoffice_mediatypes_path, notice: 'Mediatype was successfully created.' }
        format.json { render json: @mediatype, status: :created, location: @mediatype }
      else
        format.html { render action: "new" }
        format.json { render json: @mediatype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mediatypes/1
  # PUT /mediatypes/1.json
  def update
    @mediatype = Mediatype.find(params[:id])

    respond_to do |format|
      if @mediatype.update_attributes(params[:mediatype])
        format.html { redirect_to backoffice_mediatypes_path, notice: 'Mediatype was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mediatype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mediatypes/1
  # DELETE /mediatypes/1.json
  def destroy
    @mediatype = Mediatype.find(params[:id])
    @mediatype.destroy

    respond_to do |format|
      format.html { redirect_to backoffice_mediatypes_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/backoffice/activities_helper.rb
module Backoffice::ActivitiesHelper
end

app/helpers/backoffice/announces_helper.rb
module Backoffice::AnnouncesHelper
end

app/helpers/backoffice/application_helper.rb
module Backoffice::ApplicationHelper
end

app/helpers/backoffice/companies_helper.rb
module Backoffice::CompaniesHelper
end

app/helpers/backoffice/effects_helper.rb
module Backoffice::EffectsHelper
end

app/helpers/backoffice/mediatypes_helper.rb
module Backoffice::MediatypesHelper
end

app/helpers/backoffice/pages_helper.rb
module Backoffice::PagesHelper
end

app/helpers/backoffice/profiles_helper.rb
module Backoffice::ProfilesHelper
end

app/helpers/backoffice/reports_helper.rb
module Backoffice::ReportsHelper
end

app/views/backoffice/pages/_form.html.erb
<%= form_for([:backoffice,@page] , :html => {:class => "well form-horizontal"}) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
    <div class="control-label">
    <%= f.label :title %>
    </div>
    <div class="controls">
    <%= f.collection_select :parent_id, Page.all, :id, :title , :include_blank => true %>
    </div>
  </div>
  <div class="control-group">
    <div class="control-label">
    <%= f.label :title %>
    </div>
    <div class="controls">
    <%= f.text_field :title %>
    </div>
  </div>
  <div class="control-group">
    <div class="control-label">
    <%= f.label :lang %>
    </div>
    <div class="controls">
    <%= f.text_field :lang %>
    </div>
  </div>
  <div class="control-group">
    <div class="control-label">
    <%= f.label :order %>
    </div>
    <div class="controls">
    <%= f.text_field :order %>
    </div>
  </div>
  <div class="control-group">
    <div class="control-label">
    <%= f.label :content %>
    </div>
    <div class="controls">
    <%= f.text_area :content %>
    </div>
  </div>

  <div class="control-group">
    <div class="control-label">
    <%= f.label :approved %>
    </div>
    <div class="controls">
    <%= f.check_box :approved %>
    </div>
  </div>



   <div class="form-actions">
    <%= f.submit :class=>"btn btn-primary" %>
   <a href="/backoffice/pages" class="btn">Back to list</a>
 </div>

<% end %>

app/views/backoffice/pages/edit.html.erb
<div class="span9">
 <h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', [:backoffice,@page] %> |
<%= link_to 'Back', backoffice_pages_path %>
</div>

app/views/backoffice/pages/index.html.erb
<div class="span9">
 <h1>Listing pages</h1>
<ul class="nav nav-tabs">
          <li class="icon index_collection_link active" rel="" title="">
            <a href="/backoffice/pages/" class="pjax">
              <i class="icon-th-list"></i>
              <span>List</span>
            </a>
          </li>

          <li class="icon new_collection_link " rel="" title="">
            <a href="/backoffice/pages/new" class="pjax">
              <i class="icon-plus"></i>
              <span>Add new</span>
            </a>
          </li>
</ul>



<table class="table table-bordered">
  <tr>
    <th>Title</th>
    <th>Parent</th>
     <th>Order</th>
    <th>Approved</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% if @pages %>
  <% @pages.each do |page| %>
    <tr>
      <td><%= page.title %></td>
      <td><%= page.parent.title if page.parent %></td>
      <td><%= page.order %></td>
      <td><%= page.approved %></td>
      <td><%= link_to 'Show', [:backoffice,page] , :class => "btn btn-mini"%></td>
      <td><%= link_to 'Edit', edit_backoffice_page_path(page) , :class => "btn btn-mini"%></td>
      <td><%= link_to 'Destroy', [:backoffice,page], method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-mini"%></td>
    </tr>
  <% end %>
<% end %>
</table>

<br />

<!-- <%= link_to 'New Page', new_backoffice_page_path %>  -->
</div>

app/views/backoffice/pages/new.html.erb
<div class="span9">
 <h1>New page</h1>
<ul class="nav nav-tabs">
          <li class="icon index_collection_link active" rel="" title="">
            <a href="/backoffice/pages/" class="pjax">
              <i class="icon-th-list"></i>
              <span>List</span>
            </a>
          </li>

          <li class="icon new_collection_link " rel="" title="">
            <a href="/backoffice/pages/new" class="pjax">
              <i class="icon-plus"></i>
              <span>Add new</span>
            </a>
          </li>
</ul>

<%= render 'form' %>

<%= link_to 'Back', backoffice_pages_path %>
</div>

app/views/backoffice/pages/show.html.erb
<div class="span3">
  <div style="padding: 8px 0;" class="well">
    <ul class="nav nav-list">
      <li class="nav-header">List header</li>
      <% @page.children.each do |page| %>
        <li><%= link_to h(page.title),page %></li>
        <% page.children.each do |subpage| %>
          <li style="margin-left: 25px;"><%= link_to h(subpage.title),subpage %> </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div><!--/span-->




<div class="span9">
 <p id="notice"><%= notice %></p>
 
<% if can? :update, @page %>
    <p>
      <b>Title:</b>
      <%= @page.title %>
    </p>
    <p>
      <b>Approved:</b>
      <%= @page.approved %>
    </p>
    <p>
      <b>Lang:</b>
      <%= @page.lang %>
    </p>
    <p>
      <b>Lang:</b>
      <%= @page.order %>
    </p>    
    <p>
      <b>Content:</b>
    </p>  
<%end%>

<p>
  <%=raw @page.content %>

</p>

<% if can? :update, @page %>
  <%= link_to 'Edit', edit_page_path(@page) %> |
<% end %>
<br/>
<%= link_to 'Back', pages_path %>
</div>