config/routes.rb
require 'sidekiq/web'
Mrtablueline::Application.routes.draw do

  get "graphs/index"

    resources :reports
  namespace :mrta do
    resources :tracks
    resources :projects do
      get 'gentracks', on: :member
      get 'showtracks', on: :member
    end
    resources :graphs
  end

  resources :sections

  match "/progresses"  => "progresses#index"
  match "/progresses/station/:id" => "progresses#show"
  match "/progresses/report/:id" => "progresses#report"
  match "/progresses/announce/:id" => "progresses#announce"
  match "/progresses/effect/:id" => "progresses#effect"
  match "/progresses/effect/" => "progresses#effect"
  match "/progresses/effect_latest/" => "progresses#effect_latest"
  match "/progresses/effect_monthly/" => "progresses#effect_monthly"
  match "/progresses/report_latest/" => "progresses#report_latest"
  match "/progresses/report_monthly/" => "progresses#report_monthly"
  match "/progresses/activity/" => "progresses#activity"
  match "/progresses/activity_latest/" => "progresses#activity_latest"
  match "/progresses/activity_monthly/" => "progresses#activity_monthly"
  match "/fullmap" => "progresses#fullmap"

  resources :announces, :only => [:show]

  resources :activities , :only => [:show]
  resources :geopoints
  resources :pages

  namespace :admin do resources :geonodes end

  mount Ckeditor::Engine => '/ckeditor'

  get "home/index"
  get "home/underconstruction"
  get "welcome/index"
  root to: "home#index"
  get '/graph', to: "home#graph"
  mount Sidekiq::Web, at: 'sidekiq'

  match "/mrtamap" => "home#mrtamap"
  devise_for :users
  namespace :admin do
    resources :users do
      member do
        get 'assign_supervisor_role'
        get 'remove_supervisor_role'
        get 'assign_mrtaadmin_role'
        get 'remove_mrtaadmin_role'
        get 'assign_author_role'
        get 'remove_author_role'
      end
    end

  end
  namespace :backoffice do
    resources :application, :only => [:index]
    resources :pages
    resources :reports do
      get 'approve', :on => :member
    end

    resources :stations
    resources :profiles
    resources :companies
    resources :activities do
      get 'approve', :on => :member
    end

    resources :mediatypes
    resources :effects
    resources :sections
    resources :announces do
      get 'approve', :on => :member
    end
  end

   mount Ckeditor::Engine => "/ckeditor"
end

app/models/announce.rb
Stateflow.persistence = :mongoid
class Announce
  include Mongoid::Document
  include Mongoid::Timestamps
  include Log

  scope :published, ->(){where(state: :published)}
  scope :range,  ->(start, finish){
    where(:created_at => {'$gte' => start,'$lt' => finish}) if start && finish
  }
  #Announce.effect_in("Drain")
  scope :effect_in, ->(effect){
    includes(:effects).where(:"effects.name" => effect)
  }
  has_one :geopoint, as: :geoable, dependent: :destroy
  has_many :hits, as: :hitable, dependent: :destroy
  accepts_nested_attributes_for :geopoint, :allow_destroy => true
  has_and_belongs_to_many :effects
  belongs_to :user
  before_save :refresh_version
  before_update :refresh_version
  field :title, type: String
  field :content, type: String
  field :publishon, type: Date
  field :publishoff, type: Date
  field :approved, type: Boolean
  field :approvedby, type: String
  field :versions, type: String
  field :state, type: String
  #Event.daily(start, finish)
  #Event.daily(4.months.ago,Time.now)
  def self.daily(start, finish)
    daily_events = {}
    self.range(start, finish).each do |event|
      date_str = event.created_at.to_date.to_s
      daily_events[date_str] ||= 0
      daily_events[date_str] += 1
    end
    return daily_events
  end

  #State transisstions
  include  Stateflow
  stateflow do
    state_column :state
    initial   :unpublished
    state     :unpublished, :published, :archived
    event     :publish do
      transitions :from => :unpublished , :to => :published
    end
    event     :unpublish do
      transitions :from => :published, :to => :unpublished
      transitions :from => :archived, :to => :unpublished
    end
    event     :archive do
      transitions :from => :published, :to => :archived
    end
  end
  def self.search(search)
    if search
      where(title: /#{search}/)
    else
      all.desc(:created_at).to_a
    end
  end
  def hit_count
    hits.size
  end
  def unique_hit_count
    hits.group(:user_ip).size
  end

end

app/controllers/announces_controller.rb
class AnnouncesController < ApplicationController
  # GET /announces
  # GET /announces.json
  def index
    @announces = Announce.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @announces }
    end
  end

  # GET /announces/1
  # GET /announces/1.json
  def show
    @announce = Announce.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @announce }
    end
  end

  # GET /announces/new
  # GET /announces/new.json
  def new
    @announce = Announce.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @announce }
    end
  end

  # GET /announces/1/edit
  def edit
    @announce = Announce.find(params[:id])
  end

  # POST /announces
  # POST /announces.json
  def create
    @announce = Announce.new(params[:announce])

    respond_to do |format|
      if @announce.save
        format.html { redirect_to @announce, notice: 'Announce was successfully created.' }
        format.json { render json: @announce, status: :created, location: @announce }
      else
        format.html { render action: "new" }
        format.json { render json: @announce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /announces/1
  # PUT /announces/1.json
  def update
    @announce = Announce.find(params[:id])

    respond_to do |format|
      if @announce.update_attributes(params[:announce])
        format.html { redirect_to @announce, notice: 'Announce was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @announce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announces/1
  # DELETE /announces/1.json
  def destroy
    @announce = Announce.find(params[:id])
    @announce.destroy

    respond_to do |format|
      format.html { redirect_to announces_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/backoffice/announces_controller.rb
class Backoffice::AnnouncesController < ApplicationController
  layout 'backoffice'
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /announces
  # GET /announces.json
  def index
    if (current_user.has_role? :admin) or (current_user.has_role? :mrtaadmin)
      @announces = Announce.all.desc(:created_at).to_a
    else
      @announces = current_user.announces.desc(:created_at).to_a
    end


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @announces }
    end
  end

  # GET /announces/1
  # GET /announces/1.json
  def show
    @announce = Announce.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @announce }
    end
  end

  # GET /announces/new
  # GET /announces/new.json
  def new
    @announce = Announce.new
    @alleffects = Effect.all.to_a
    @selectedeffect = Effect.all.to_a.first
    @announce.build_geopoint
    @lat = 13.7522222
    @lng = 100.4938889
    @json = '[{"lng": "100.4938889", "lat": "13.7522222"}]'


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @announce }
    end
  end

  # GET /announces/1/edit
  def edit
    Announce
    @announce = Announce.find(params[:id]) rescue nil
    @alleffects = Effect.all.to_a
    @json = @announce.geopoint.to_gmaps4rails
  end

  # POST /announces
  # POST /announces.json
  def create
    @announce = Announce.new(params[:announce])
    @announce.user_id = current_user._id

    respond_to do |format|
      if @announce.save
        ApproveSystem.perform_async(@announce.id,'announces','Announce')
        format.html { redirect_to backoffice_announces_path, notice: 'Announce was successfully created.' }
        format.json { render json: @announce, status: :created, location: @announce }
      else
        format.html { render action: "new" }
        format.json { render json: @announce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /announces/1
  # PUT /announces/1.json
  def update
    @announce = Announce.find(params[:id])

    respond_to do |format|
      if @announce.update_attributes(params[:announce])
        format.html { redirect_to backoffice_announces_path, notice: 'Announce was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @announce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announces/1
  # DELETE /announces/1.json
  def destroy
    @announce = Announce.find(params[:id])
    @announce.destroy

    respond_to do |format|
      format.html { redirect_to backoffice_announces_url }
      format.json { head :no_content }
    end
  end
  def approve
    @announce = Announce.find(params[:id])
    if @announce.approved
       @announce.approved = false
    @announce.approvedby= "unapproved #{current_user.name || current_user.email}"  + Time.now.strftime("on %m/%d/%Y at %I:%M%p")
    else
       @announce.approved = true
       @announce.approvedby= "approved #{current_user.name || current_user.email}"  + Time.now.strftime("on %m/%d/%Y at %I:%M%p")

    end

    @announce.save
    respond_to do |format|
      format.html { redirect_to backoffice_announces_path }
    end
  end
end

app/helpers/announces_helper.rb
module AnnouncesHelper
end

app/helpers/backoffice/announces_helper.rb
module Backoffice::AnnouncesHelper
end

app/views/announces/_announce.html.erb
<li>
  <% if announce %>
    <a href="/progresses/announce/<%= announce.id %>">
      <%= announce.title %>
    </a>
  <% else %>
    <a> ไม่พบรายการที่ค้นหา </a>
  <% end %>
</li>

app/views/announces/_form.html.erb
<%= form_for(@announce) do |f| %>
  <% if @announce.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announce.errors.count, "error") %> prohibited this announce from being saved:</h2>

      <ul>
      <% @announce.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :publishon %><br />
    <%= f.date_select :publishon %>
  </div>
  <div class="field">
    <%= f.label :publishoff %><br />
    <%= f.date_select :publishoff %>
  </div>
  <div class="field">
    <%= f.label :approved %><br />
    <%= f.check_box :approved %>
  </div>
  <div class="field">
    <%= f.label :approvedby %><br />
    <%= f.text_field :approvedby %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announces/edit.html.erb
<h1>Editing announce</h1>

<%= render 'form' %>

<%= link_to 'Show', @announce %> |
<%= link_to 'Back', announces_path %>

app/views/announces/index.html.erb
<h1>Listing announces</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Publishon</th>
    <th>Publishoff</th>
    <th>Approved</th>
    <th>Approvedby</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


<% @announces.each do |announce| %>
  <tr>
    <td><%= announce.title %></td>
    <td><%= announce.content %></td>
    <td><%= announce.publishon %></td>
    <td><%= announce.publishoff %></td>
    <td><%= announce.approved %></td>
    <td><%= announce.approvedby %></td>
    <td><%= link_to 'Show', announce %></td>
    <td><%= link_to 'Edit', edit_announce_path(announce) %></td>
    <td><%= link_to 'Destroy', announce, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Announce', new_announce_path %>

app/views/announces/new.html.erb
<h1>New announce</h1>

<%= render 'form' %>

<%= link_to 'Back', announces_path %>

app/views/announces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @announce.title %>
</p>

<p>
  <b>Content:</b>
  <%= @announce.content %>
</p>

<p>
  <b>Publishon:</b>
  <%= @announce.publishon %>
</p>

<p>
  <b>Publishoff:</b>
  <%= @announce.publishoff %>
</p>

<p>
  <b>Approved:</b>
  <%= @announce.approved %>
</p>

<p>
  <b>Approvedby:</b>
  <%= @announce.approvedby %>
</p>


<%= link_to 'Edit', edit_announce_path(@announce) %> |
<%= link_to 'Back', announces_path %>