config/routes.rb
require 'sidekiq/web'
Mrtablueline::Application.routes.draw do

  get "graphs/index"

    resources :reports
  namespace :mrta do
    resources :tracks
    resources :projects do
      get 'gentracks', on: :member
      get 'showtracks', on: :member
    end
    resources :graphs
  end

  resources :sections

  match "/progresses"  => "progresses#index"
  match "/progresses/station/:id" => "progresses#show"
  match "/progresses/report/:id" => "progresses#report"
  match "/progresses/announce/:id" => "progresses#announce"
  match "/progresses/effect/:id" => "progresses#effect"
  match "/progresses/effect/" => "progresses#effect"
  match "/progresses/effect_latest/" => "progresses#effect_latest"
  match "/progresses/effect_monthly/" => "progresses#effect_monthly"
  match "/progresses/report_latest/" => "progresses#report_latest"
  match "/progresses/report_monthly/" => "progresses#report_monthly"
  match "/progresses/activity/" => "progresses#activity"
  match "/progresses/activity_latest/" => "progresses#activity_latest"
  match "/progresses/activity_monthly/" => "progresses#activity_monthly"
  match "/fullmap" => "progresses#fullmap"

  resources :announces, :only => [:show]

  resources :activities , :only => [:show]
  resources :geopoints
  resources :pages

  namespace :admin do resources :geonodes end

  mount Ckeditor::Engine => '/ckeditor'

  get "home/index"
  get "home/underconstruction"
  get "welcome/index"
  root to: "home#index"
  get '/graph', to: "home#graph"
  mount Sidekiq::Web, at: 'sidekiq'

  match "/mrtamap" => "home#mrtamap"
  devise_for :users
  namespace :admin do
    resources :users do
      member do
        get 'assign_supervisor_role'
        get 'remove_supervisor_role'
        get 'assign_mrtaadmin_role'
        get 'remove_mrtaadmin_role'
        get 'assign_author_role'
        get 'remove_author_role'
      end
    end

  end
  namespace :backoffice do
    resources :application, :only => [:index]
    resources :pages
    resources :reports do
      get 'approve', :on => :member
    end

    resources :stations
    resources :profiles
    resources :companies
    resources :activities do
      get 'approve', :on => :member
    end

    resources :mediatypes
    resources :effects
    resources :sections
    resources :announces do
      get 'approve', :on => :member
    end
  end

   mount Ckeditor::Engine => "/ckeditor"
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  layout 'content'
  before_filter  :log_hit, :only => [:show]
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
    @announces = Announce.search(params[:search])
    @announces10 = Announce.desc(:created_at).limit(25).to_a
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activities = Activity.all.desc(:created_at)
    @activity = Activity.find(params[:id])
    @announces = Announce.search(params[:search])
    @announces10 = Announce.desc(:created_at).limit(25).to_a
    @traffics = Effect.where(name: "Traffic").first.announces  rescue nil
    @sounds = Effect.where(name: "Sound").first.announces  rescue nil
    @vibrations = Effect.where(name: "Vibration").first.announces rescue nil
    @dusts = Effect.where(name: "Dust").first.announces rescue nil
    @drains = Effect.where(name: "Drain").first.announces rescue nil

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end
  private
  def log_hit
    @userip = request.env['REMOTE_ADDR']
    @activity = Activity.find(params[:id])
    @activity.hits.create(user_ip: @userip)
  end

end

app/controllers/backoffice/activities_controller.rb
class Backoffice::ActivitiesController < ApplicationController
  layout 'backoffice'
  before_filter :authenticate_user!
  load_and_authorize_resource
    # GET /activities
  # GET /activities.json
  def index
    if (current_user.has_role? :admin) or (current_user.has_role? :mrtaadmin)
      @activities = Activity.unscoped.all.desc(:created_at).to_a
    else
      @activities = current_user.activities.unscoped.desc(:created_at).to_a

    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show

    if (current_user.has_role? :admin) or (current_user.has_role? :mrtaadmin)
      @activity = Activity.find(params[:id])
    else
      @activity = current_user.activities.find(params[:id])
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new
    @allmedias = Mediatype.all
    @selectedmedia = Mediatype.all.to_a.first
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
    @allmedias = Mediatype.all
    @selectedmedia = @activity.mediatype
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])
    @activity.user_id = current_user._id
    respond_to do |format|
      if @activity.save
        ApproveSystem.perform_async(@activity.id,'activities','Activity')
        format.html { redirect_to backoffice_activities_path, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to backoffice_activities_path, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to backoffice_activities_url }
      format.json { head :no_content }
    end
  end
  def approve
    @activity = Activity.find(params[:id])
    if @activity.approved
       @activity.approved = false
    @activity.approvedby= "unapproved #{current_user.name || current_user.email}"  + Time.now.strftime("on %m/%d/%Y at %I:%M%p")
    else
       @activity.approved = true
       @activity.approvedby= "approved #{current_user.name || current_user.email}"  + Time.now.strftime("on %m/%d/%Y at %I:%M%p")

    end

    @activity.save
    respond_to do |format|
      format.html { redirect_to backoffice_activities_path }
    end
  end

end

app/controllers/backoffice/announces_controller.rb
class Backoffice::AnnouncesController < ApplicationController
  layout 'backoffice'
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /announces
  # GET /announces.json
  def index
    if (current_user.has_role? :admin) or (current_user.has_role? :mrtaadmin)
      @announces = Announce.all.desc(:created_at).to_a
    else
      @announces = current_user.announces.desc(:created_at).to_a
    end


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @announces }
    end
  end

  # GET /announces/1
  # GET /announces/1.json
  def show
    @announce = Announce.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @announce }
    end
  end

  # GET /announces/new
  # GET /announces/new.json
  def new
    @announce = Announce.new
    @alleffects = Effect.all.to_a
    @selectedeffect = Effect.all.to_a.first
    @announce.build_geopoint
    @lat = 13.7522222
    @lng = 100.4938889
    @json = '[{"lng": "100.4938889", "lat": "13.7522222"}]'


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @announce }
    end
  end

  # GET /announces/1/edit
  def edit
    Announce
    @announce = Announce.find(params[:id]) rescue nil
    @alleffects = Effect.all.to_a
    @json = @announce.geopoint.to_gmaps4rails
  end

  # POST /announces
  # POST /announces.json
  def create
    @announce = Announce.new(params[:announce])
    @announce.user_id = current_user._id

    respond_to do |format|
      if @announce.save
        ApproveSystem.perform_async(@announce.id,'announces','Announce')
        format.html { redirect_to backoffice_announces_path, notice: 'Announce was successfully created.' }
        format.json { render json: @announce, status: :created, location: @announce }
      else
        format.html { render action: "new" }
        format.json { render json: @announce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /announces/1
  # PUT /announces/1.json
  def update
    @announce = Announce.find(params[:id])

    respond_to do |format|
      if @announce.update_attributes(params[:announce])
        format.html { redirect_to backoffice_announces_path, notice: 'Announce was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @announce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announces/1
  # DELETE /announces/1.json
  def destroy
    @announce = Announce.find(params[:id])
    @announce.destroy

    respond_to do |format|
      format.html { redirect_to backoffice_announces_url }
      format.json { head :no_content }
    end
  end
  def approve
    @announce = Announce.find(params[:id])
    if @announce.approved
       @announce.approved = false
    @announce.approvedby= "unapproved #{current_user.name || current_user.email}"  + Time.now.strftime("on %m/%d/%Y at %I:%M%p")
    else
       @announce.approved = true
       @announce.approvedby= "approved #{current_user.name || current_user.email}"  + Time.now.strftime("on %m/%d/%Y at %I:%M%p")

    end

    @announce.save
    respond_to do |format|
      format.html { redirect_to backoffice_announces_path }
    end
  end
end

app/controllers/backoffice/application_controller.rb
class Backoffice::ApplicationController < ApplicationController
  layout 'backoffice'
  before_filter :authenticate_user!
   #load_and_authorize_resource

  def index
  end
  protected

    def ckeditor_filebrowser_scope(options = {})
      super({ :assetable_id => current_user.id, :assetable_type => 'User' }.merge(options))
    end
end

app/controllers/backoffice/companies_controller.rb
class Backoffice::CompaniesController < ApplicationController
  layout 'backoffice'
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to backoffice_companies_path, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to backoffice_companies_path, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to backoffice_companies_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/backoffice/effects_controller.rb
class Backoffice::EffectsController < ApplicationController
  layout 'backoffice'
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /effects
  # GET /effects.json
  def index
    @effects = Effect.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @effects }
    end
  end

  # GET /effects/1
  # GET /effects/1.json
  def show
    @effect = Effect.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @effect }
    end
  end

  # GET /effects/new
  # GET /effects/new.json
  def new
    @effect = Effect.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @effect }
    end
  end

  # GET /effects/1/edit
  def edit
    @effect = Effect.find(params[:id])
  end

  # POST /effects
  # POST /effects.json
  def create
    @effect = Effect.new(params[:effect])

    respond_to do |format|
      if @effect.save
        format.html { redirect_to backoffice_effects_path, notice: 'Effect was successfully created.' }
        format.json { render json: @effect, status: :created, location: @effect }
      else
        format.html { render action: "new" }
        format.json { render json: @effect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /effects/1
  # PUT /effects/1.json
  def update
    @effect = Effect.find(params[:id])

    respond_to do |format|
      if @effect.update_attributes(params[:effect])
        format.html { redirect_to backoffice_effects_path, notice: 'Effect was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @effect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /effects/1
  # DELETE /effects/1.json
  def destroy
    @effect = Effect.find(params[:id])
    @effect.destroy

    respond_to do |format|
      format.html { redirect_to backoffice_effects_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/backoffice/activities_helper.rb
module Backoffice::ActivitiesHelper
end

app/helpers/backoffice/announces_helper.rb
module Backoffice::AnnouncesHelper
end

app/helpers/backoffice/application_helper.rb
module Backoffice::ApplicationHelper
end

app/helpers/backoffice/companies_helper.rb
module Backoffice::CompaniesHelper
end

app/helpers/backoffice/effects_helper.rb
module Backoffice::EffectsHelper
end

app/helpers/backoffice/mediatypes_helper.rb
module Backoffice::MediatypesHelper
end

app/views/backoffice/activities/_form.html.erb
<%= form_for([:backoffice,@activity] , :html => {:class => "well form-horizontal"}) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% @activity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
    <div class="control-label">
      <%= f.label :mediatype %>
    </div>
    <div class="controls">
      <% if @selectedmedia %>
         <% @selectmediaid = @selectedmedia._id  %>
       <% else %>
         <% @selectmediaid = ""  %>
       <% end %>
      <%= f.collection_select :mediatype_id, @allmedias, :id, :name_th, {:selected => @selectmediaid,:include_blank => "No media type"} %>
    </div>
  </div>

  <div class="control-group">
    <div class="control-label">
      <%= f.label :title %>
    </div>
    <div class="controls">
      <%= f.text_field :title, :style => "width: 500px" %>
    </div>
  </div>
  <div class="control-group">
    <div class="control-label">
      <%= f.label :intro %>
    </div>
    <div class="controls">
      <%= f.text_field :intro,:style => "width: 500px;" %>
    </div>
  </div>

  <div class="control-group">
    <div class="control-label">
      <%= f.label :content %>
    </div>
    <div class="controls">
      <%= f.text_area :content %>
    </div>
  </div>
  <div class="control-group">
    <div class="control-label">
      <%= f.label :publishon %>
    </div>
    <div class="controls">
      <%= f.text_field :publishon %>
    </div>
  </div>
  <div class="control-group">
    <div class="control-label">
      <%= f.label :publishoff %>
    </div>
    <div class="controls">
      <%= f.text_field :publishoff %>
    </div>
  </div>
  <!--
  <div class="control-group">
    <div class="control-label">
      <%= f.label :approved %>
    </div>
    <div class="controls">
      <%= f.check_box :approved %>
    </div>
  </div>
  <div class="control-group">
    <div class="control-label">
      <%= f.label :approvedby %>
    </div>
    <div class="controls">
      <%= f.text_field :approvedby %>
    </div>
  </div>
  -->
  <div class="form-actions">
    <%= f.submit :class=>"btn btn-primary" %>
    <a href="/backoffice/activities" class="btn">Back to list</a>
  </div>

<% end %>

app/views/backoffice/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', [:backoffice,@activity] %> |
<%= link_to 'Back', backoffice_activities_path %>

app/views/backoffice/activities/index.html.erb
<h1>Listing activities</h1>
<ul class="nav nav-tabs">
          <li class="icon index_collection_link active" rel="" title="">
            <a href="/backoffice/activities/" class="pjax">
              <i class="icon-th-list"></i>
              <span>List</span>
            </a>
          </li>

          <li class="icon new_collection_link " rel="" title="">
            <a href="/backoffice/activities/new" class="pjax">
              <i class="icon-plus"></i>
              <span>Add new</span>
            </a>
          </li>
</ul>

<table class="table table-bordered">
  <tr>
    <th>No</th>
    <th>Title</th>
    <th>Publishon</th>
    <th>Publishoff</th>
    <th>Approved</th>
    <th>Approvedby</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% if @activities %>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.created_at.strftime("%m/%d/%Y") %></td>
        <td><%= activity.title %> <br> โดย <small> <%= activity.user.name if activity.user %> </small></td>
        <td><%= activity.publishon %></td>
        <td><%= activity.publishoff %></td>
        <td><%= activity.approved %></td>
        <td><%= activity.approvedby %></td>
        <td><%= link_to 'Show', [:backoffice,activity], :class => "btn btn-mini" %></td>

        <% if can? :update, activity %>
          <td><%= link_to 'Edit', edit_backoffice_activity_path(activity) , :class => "btn btn-mini" %></td>
        <% end %>

        <% if can? :destroy, activity %>
          <td><%= link_to 'Destroy', [:backoffice,activity], method: :delete, data: { confirm: 'Are you sure?' } ,:class => "btn btn-mini" %></td>
        <% if can? :manage , activity %>
          <%  if activity.approved %>
            <% msg = 'unapproved' %>
          <% else %>
            <% msg = 'approved' %>
          <% end %>
          <td><%= link_to "#{msg}", approve_backoffice_activity_path(activity), :class => "btn btn-mini" %></td>
        <% end %>

        <% end %>
      </tr>
    <% end %>
  <% end %>
</table>

<br />
<%= link_to 'New Activity', new_backoffice_activity_path %>

app/views/backoffice/activities/new.html.erb
<div class="span9">
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', backoffice_activities_path %>

</div>

app/views/backoffice/activities/show.html.erb
<div class="span9">
<p id="notice"><%= notice %></p>
<p class="well">
  <b>Title:</b>
  <%= @activity.title %>
  <br>
  <b>Intro:</b>
  <%= @activity.intro %>
</p>

<p>
  <b>Content:</b>
  <%=raw @activity.content %>
</p>

<p>
  <b>Publishon:</b>
  <%= @activity.publishon %>
</p>

<p>
  <b>Publishoff:</b>
  <%= @activity.publishoff %>
</p>

<p>
  <b>Approved:</b>
  <%= @activity.approved %>
</p>

<p>
  <b>Approvedby:</b>
  <%= @activity.approvedby %>
</p>
<p>
  <b>FromMedia:</b>
  <% if  @activity.mediatype  %>
      <%= image_tag @activity.mediatype.medialogo.url(:thumb160x120)  %>
    <% else %>
      <p>Sorry no image for media!!!</p>
  <% end %>
</p>
<p>
  <b>issued:</b>
  <%= @activity.issue_no %>
</p>

<%= link_to 'Edit', edit_backoffice_activity_path(@activity) %> |
<%= link_to 'Back', backoffice_activities_path %>

</div>