config/routes.rb
require 'sidekiq/web'
Mrtablueline::Application.routes.draw do

  get "graphs/index"

    resources :reports
  namespace :mrta do
    resources :tracks
    resources :projects do
      get 'gentracks', on: :member
      get 'showtracks', on: :member
    end
    resources :graphs
  end

  resources :sections

  match "/progresses"  => "progresses#index"
  match "/progresses/station/:id" => "progresses#show"
  match "/progresses/report/:id" => "progresses#report"
  match "/progresses/announce/:id" => "progresses#announce"
  match "/progresses/effect/:id" => "progresses#effect"
  match "/progresses/effect/" => "progresses#effect"
  match "/progresses/effect_latest/" => "progresses#effect_latest"
  match "/progresses/effect_monthly/" => "progresses#effect_monthly"
  match "/progresses/report_latest/" => "progresses#report_latest"
  match "/progresses/report_monthly/" => "progresses#report_monthly"
  match "/progresses/activity/" => "progresses#activity"
  match "/progresses/activity_latest/" => "progresses#activity_latest"
  match "/progresses/activity_monthly/" => "progresses#activity_monthly"
  match "/fullmap" => "progresses#fullmap"

  resources :announces, :only => [:show]

  resources :activities , :only => [:show]
  resources :geopoints
  resources :pages

  namespace :admin do resources :geonodes end

  mount Ckeditor::Engine => '/ckeditor'

  get "home/index"
  get "home/underconstruction"
  get "welcome/index"
  root to: "home#index"
  get '/graph', to: "home#graph"
  mount Sidekiq::Web, at: 'sidekiq'

  match "/mrtamap" => "home#mrtamap"
  devise_for :users
  namespace :admin do
    resources :users do
      member do
        get 'assign_supervisor_role'
        get 'remove_supervisor_role'
        get 'assign_mrtaadmin_role'
        get 'remove_mrtaadmin_role'
        get 'assign_author_role'
        get 'remove_author_role'
      end
    end

  end
  namespace :backoffice do
    resources :application, :only => [:index]
    resources :pages
    resources :reports do
      get 'approve', :on => :member
    end

    resources :stations
    resources :profiles
    resources :companies
    resources :activities do
      get 'approve', :on => :member
    end

    resources :mediatypes
    resources :effects
    resources :sections
    resources :announces do
      get 'approve', :on => :member
    end
  end

   mount Ckeditor::Engine => "/ckeditor"
end

app/models/report.rb
class Report
  include Mongoid::Document
  include Mongoid::Timestamps
  has_one :geopoint, as: :geoable, dependent: :destroy
  has_many :hits, as: :hitable, dependent: :destroy
  embeds_many :images, :cascade_callbacks => true
  accepts_nested_attributes_for :geopoint, :allow_destroy => true
  accepts_nested_attributes_for :images, :allow_destroy => true
  has_and_belongs_to_many :effects
  belongs_to :user
  belongs_to :station
  field :title, type: String
  field :content, type: String
  field :publishon, type: Date
  field :publishoff, type: Date
  field :approved, type: Boolean
  field :approvedby, type: String

  def hit_count
    hits.size
  end
  def unique_hit_count
    hits.group(:user_ip).size
  end
end

app/controllers/backoffice/reports_controller.rb
class Backoffice::ReportsController < ApplicationController
  layout 'backoffice'
  before_filter :authenticate_user!
  load_and_authorize_resource
  def index
    if (current_user.has_role? :admin) or (current_user.has_role? :mrtaadmin)
      @reports = Report.all.desc(:created_at).to_a
    else
      current_user.reports.desc(:created_at).to_a
    end


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new
    @report.build_geopoint
    @lat = 13.7522222
    @lng = 100.4938889
    @json = '[{"lng": "100.4938889", "lat": "13.7522222"}]'
    @allstations = Station.all
    @selectedstation = Station.all.to_a.first

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
    @json = @report.geopoint.to_gmaps4rails
    @allstations = Station.all
    @selectedstation = @report.station

  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(params[:report])
    @report.user_id = current_user._id
    respond_to do |format|
      if @report.save
        ApproveSystem.perform_async(@report.id,'reports','Report')
        format.html { redirect_to backoffice_reports_path, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to backoffice_reports_path, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to backoffice_reports_url }
      format.json { head :no_content }
    end
  end
  def show_map

  end
  def approve
    @report = Report.find(params[:id])
    if @report.approved
       @report.approved = false
    @report.approvedby= "unapproved #{current_user.name || current_user.email}"  + Time.now.strftime("on %m/%d/%Y at %I:%M%p")
    else
       @report.approved = true
       @report.approvedby= "approved #{current_user.name || current_user.email}"  + Time.now.strftime("on %m/%d/%Y at %I:%M%p")

    end

    @report.save
    respond_to do |format|
      format.html { redirect_to backoffice_reports_path }
    end
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  load_and_authorize_resource
  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new
    @report.build_geopoint
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(params[:report])

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/backoffice/reports_helper.rb
module Backoffice::ReportsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= nested_form_for(@report,:html=>{:multipart => true }) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :publishon %><br />
    <%= f.text_field :publishon %>
  </div>
  <div class="field">
    <%= f.label :publishoff %><br />
    <%= f.text_field :publishoff %>
  </div>
  <div class="field">
    <%= f.label :approved %><br />
    <%= f.check_box :approved %>
  </div>
  <div class="field">
    <%= f.label :approvedby %><br />
    <%= f.text_field :approvedby %>
  </div>



  <%= f.fields_for :geopoints do |geo| %>
    <%= geo.label :name %> <%= geo.text_field :name %> <br/>
    <%= geo.label :city %> <%= geo.text_field :city %> <br/>
    <%= geo.label :country %><%= geo.text_field :country %> <br />
    <%= geo.label :latitude %><%= geo.text_field :latitude %> <br />
    <%= geo.label :longitude %><%= geo.text_field :longitude %> <br />
      <%= geo.label :gmaps %><%= geo.text_field :gmaps %>

      <%= geo.link_to_remove "Remove this Geo" %>
   <%end  %>
   <p><%= f.link_to_add "Add geopoint", :geopoints %></p>

  <%= f.fields_for :images do |image| %>
  <div class="field">
    <%= image.label :title %><br />
    <%= image.text_field :title %>
  </div>
  <div class="field">
    <%= image.label :image %><br />
    <%= image.file_field :image %>
  </div>
 <%= image.link_to_remove  "remove Image"  %>
  <% end %>

  <p><%= f.link_to_add "Add images", :images %></p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Publishon</th>
    <th>Publishoff</th>
    <th>Approved</th>
    <th>Approvedby</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%= report.title %></td>
    <td><%= report.content %></td>
    <td><%= report.publishon %></td>
    <td><%= report.publishoff %></td>
    <td><%= report.approved %></td>
    <td><%= report.approvedby %></td>
    <td><%= link_to 'Show', report %></td>
    <% if can? :update, report %>
       <td><%= link_to 'Edit', edit_report_path(report) %></td>
    <% end %>
    <% if can? :destroy, report %>
      <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
    </tr>
<% end %>
</table>

<br />

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @report.title %>
</p>

<p>
  <b>Content:</b>
  <%= @report.content %>
</p>

<p>
  <b>Publishon:</b>
  <%= @report.publishon %>
</p>

<p>
  <b>Publishoff:</b>
  <%= @report.publishoff %>
</p>

<p>
  <b>Approved:</b>
  <%= @report.approved %>
</p>

<p>
  <b>Approvedby:</b>
  <%= @report.approvedby %>
</p>

  <% @report.geopoints.each do |geo| %>
    <%= geo.name %>
    <%= geo.city%>
    <%= geo.country %>
    <%= geo.latitude %>
    <%= geo.longitude %>
    <%= geo.gmaps %>
  <% end %>
  <% @jsons = @report.geopoints.to_gmaps4rails %>
<% @report.images.each do  |img| %>
  <%= image_tag img.image.url %>
<%= image_tag img.image.url(:thumb50x50) %>
<%= image_tag img.image.url(:thumb160x120) %>
<%= image_tag img.image.url(:thumb260x180) %>
<%= image_tag img.image.url(:thumb360x268) %>

<% end %>

  <%= gmaps4rails(@jsons) %>

  <% if can? :update, @report %>
     <%= link_to 'Edit', edit_report_path(@report) %> |
  <% end %>
<%= link_to 'Back', reports_path %>